spring:
  application:
    name: plateful
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/plateful
    username: viba
    password: secret
  sql:
    init:
      mode: never

logging:
  level:
    org.springframework.r2dbc: DEBUG
